### PR TITLE
Feature/manage configurations fixes #5 and #3

### LINKED ISSUE #5: Support multiple saved configurations
Feature request: allow saving a configuration with an associated name, for later recall. Thus you could have one configuration for diceware, one for the alternate diceware list, one for secure sites that need 10 words, one for sites where 5-6 words is plenty, etc.

Bonus points: add these configurations as separate custom algorithms or generators, so that they can be accessed without even going into the settings dialog for WordSequencer.

I'm not sure how to mark this as a feature request/enhancement, maybe I don't have appropriate access rights to do that.

### PR DESCRIPTION
**Pull request by fireout**
Fixes #5 and #3 
Also saving using File/Save will tie the configuration to the current keepass password profile

### CODE REVIEW

**Comment by fireout** [comment]
@fritzophrenic can you try it out when you have a chance and tell me what you think?

**Comment by fritzophrenic** [comment]
I'll try to check it out this week, thanks!

**Comment by fireout** [comment]
I updated the [documentation](https://github.com/fireout/keepasssequencer/wiki/2.-Basic-Configuration) and included the templates and load/save feature.  Can you tell me if it makes sense?

**Comment by fritzophrenic** [comment]
I've merged this into my current work to play with it some this week. I'll let you know what I think soon!

**Comment by fritzophrenic** [comment]
I like the way you handled the top5k words, with the popup providing a link back. Actually the auto-population of the word list is pretty cool by itself. I haven't looked at the code yet to see how that's handled, I assume the word list isn't hard-coded but comes from the config files you added. It would be cool if those could be picked up automatically based on which files are present; right now it looks like there were some functions added specific to each list. That's probably fine for the time being though. It looks like the NGSL list needs some pruning to remove variants of the same word.

For save/load, I seem to be doing something wrong: I don't notice anything happening when I save or load a configuration. A dialog pops up asking for a name, but after I save the configuration, I don't see it appear in any menu or anything. When I delete or change the word list after saving, and do a load, I can type in the same name, but nothing on the configuration page changes in any way.

I did try this compiled directly from the feature/manage-configurations branch, so it doesn't appear to be something I introduced in my merge with my own work.

Am I using this feature wrong? I'd expect a list of previously saved configuration names on the save/load dialogs so I could select one to overwrite or load. On loading, I'd expect all the settings on the configuration dialog to be restored to the saved state. I don't need to give full file paths, do I?

Additionally, it would be nice (though maybe a different feature addition) to add saved configurations to the algorithm list, so that you could save profiles in KeePass that reference the different WordSequencer configurations. I.e. add them to this list:
algorithm_list

**Comment by fireout** [comment]
The save actually creates another file (with the specified name happended to the userConfigPath filepath) it should later be reloadable using the same name.
Saving a file also associate it with the Keepass **Profile** (not the algorythm). You should be able to save multiple keepass profile with sequencer saved config associated with it.

You are right though, it's missing some user feedback, I'll add a dialog or a message...

Hope this help, please tell me if you get it working.  I will create a ticket for listing saved configs if you do, otherwise maybe I should make it more intuitive within this changes set.

**Comment by fireout** [comment]
Last commit resolves #16 and enhanced loading experience (see #24)

I added previously found saved file within the load menu item. @fritzophrenic tell me if this help resolving the issue you had with loading and saving files, thanks.

**Comment by fireout** [comment]
I'll merge this PR for now,  We can add issues if anything still needs to be resolved

**Comment by fritzophrenic** [comment]
> I added previously found saved file within the load menu item. @fritzophrenic tell me if this help resolving the issue you had with loading and saving files, thanks.

Yes, this helps a lot. I guess I must have needed the full file path on the load screen but only the name on the save screen? Anyway I can save and load configs now.

This _may_ be more user-friendly to show only the short name (e.g. "myconfig") rather that the full file path in the load menu. The only benefit I can think of for the full file path is users can back up saved configurations more easily if they know where they are.

> Saving a file also associate it with the Keepass Profile (not the algorythm). You should be able to save multiple keepass profile with sequencer saved config associated with it.

I'm not sure what this means. If I save a profile, I can generate a password using that profile without actually opening the password generator tool. That's basically what I want to be able to do with saved Word Sequencer configurations. I'm not sure how I would go about associating a saved configuration with a profile with the current state of the plugin. Am I missing something?
generate_from_profile

**Pull request merged**
