### PR TITLE
Disable options that reduce password strength

### LINKED ISSUE #22: Remove options that decrease password security?
I was thinking about the "length strength" for characters and percentage options for words, and it seems that these options add a tiny bit more randomness, for big potential sacrifices in password security. I asked on the Security Stack Exchange about the [entropy calculation for variable-length password generation schemes](http://security.stackexchange.com/q/107236/93625) for my entropy bar branch (almost done, sorry I've been busy for a while) and confirmed that these options probably are not worth using.

Is there any reason to include these, aside from backwards compatibility? I think the interface for setting these should probably be removed, if not the capability itself.

The only way I could see these being useful, would be for an either-or type of sequence item (e.g. choose a word from list 1 with 50% probability, otherwise choose a word from list 2), but the options would need reworking to support that anyway. Right now I think the options just complicate the interface, and sacrifice security.

### PR DESCRIPTION
**Pull request by fireout**
This fixes #22 

Added advanced mode menu.
Fix serialization problem.
Added dialog to confirm usage or advanced mode.

### CODE REVIEW

**Comment by fireout** [comment]
@fritzophrenic can you confirm this is good enough for #22?

We already had the feature implemented in the ui, so I figured might as well keep it; and display the same message to enable the relevant controls.

Thanks

**Comment by fritzophrenic** [comment]
When I pulled this into my branch I had to fix what looked like an incomplete merge, but after that it works great! I think the "advanced mode" is a good solution for removing those options for most people.

I am not very fond of the "Advanced mode is activated, generated password may end up being weak" message. I think we have warned the user enough after the first warning dialog, showing this message when generating a password may be overkill. But I only got it once, so I'm not 100% clear on the conditions to show it. It's no big deal if you want to leave it in.

I did see a glitch with the file load menu, I'll write a new issue with that.

**Comment by fritzophrenic** [comment]
I did notice a big block of commented-out code in MainForm.cs. That should probably go away before closing this pull request all the way.

**Comment by fireout** [comment]
> When I pulled this into my branch I had to fix what looked like an incomplete merge...

You are right, I do not have a visual tool for managing conflicts, I must have forgotten some.  I'll try to fix this soon.

The message should show the first time a sequence config using advanced config is used to generate a password, for every instance of KeePass.  We clear the flag when we modify the sequence though, so it pops again generating a "freshly" saved config.

I should probably move the message to when saving a file with advanced options activated instead of when generating password... it will be less invasive and will remind that this config has the option enabled when we save it...  What do you think?

**Comment by fritzophrenic** [comment]
> I should probably move the message to when saving a file with advanced options activated instead of when generating password... it will be less invasive and will remind that this config has the option enabled when we save it... What do you think?

That makes more sense.

**Comment by fritzophrenic** [comment]
> > When I pulled this into my branch I had to fix what looked like an incomplete merge...
> 
> You are right, I do not have a visual tool for managing conflicts,

Do you prefer not to use one, or do you just not have one right now? I like kdiff3 on Windows, if you're looking for one. It's powerful with features like manual alignment, joining and splitting diffs, and specifying pre-processor commands; it's a 3-way diff tool with a "base" revision in addition to the "local" and "remote"; and it's completely free.

**Comment by fireout** [comment]
Thanks, I'll have a look at it.

**Pull request merged**
